# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

sudo: false
warnings_are_errors: false

matrix:
  include:
    - os: linux
      r: release

    - os: linux
      r: devel

    - os: osx
      r: release

    - os: osx
      r: devel

r_packages:
- cowplot
- DT
- ggplot2
- ggpubr
- nlme
- shiny
- tidyr
- golem
- covr
- testthat
- RSelenium
- shinytest
#- packrat/lib
#- travis_phantomjs


r_build_args: "--no-manual --no-resave-data"
r_check_args: "--as-cran --no-build-vignettes --no-manual --timings"

env:
  global:
  - _R_CHECK_TIMINGS_="0"
  - MOZ_HEADLESS=1
  
addons:
  firefox: latest


script:
- Rscript vici/R/run_app.R &
#  - R -f inst/app/tests/run_shinyTest.R
# only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
  
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep_history: true
#  on:
#    branch: test_deploy