# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

sudo: false
warnings_are_errors: false

r:
- release
- devel

os:
- linux
- osx

r_packages:
- DT
- ggplot2
- grDevices
- magrittr
- ggpubr
- nlme
- shiny
- stats
- utils

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--as-cran --no-build-vignettes --no-manual --timings"

env:
  global:
  - _R_CHECK_TIMINGS_="0"
