# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

sudo: false
warnings_are_errors: false

services:
  - docker

matrix:
  include:
    - os: linux
      r: release

    - os: linux
      r: devel

    #- os: osx
    #  r: release

    #- os: osx
    #  r: devel

r_packages:
- cowplot
- DT
- ggplot2
- ggpubr
- nlme
- shiny
- tidyr
- golem
- covr
- testthat
- RSelenium
- devtools


r_build_args: "--no-manual --no-resave-data"
r_check_args: "--as-cran --no-build-vignettes --no-manual --timings --no-tests"

env:
  global:
  - _R_CHECK_TIMINGS_="0"
  - MOZ_HEADLESS=1

addons:
  firefox: latest

before_install:
  - docker pull selenium/standalone-firefox:2.53.0
  - docker run -d -p 127.0.0.1:4455:4444 selenium/standalone-firefox:2.53.0
#  - docker build -t rocker/tidyverse .
#  - docker run -d -p 127.0.0.1:80:4567 rocker/tidyverse /bin/sh -c "cd /root/tidyverse; bundle exec foreman start;"
#  - docker ps -a
#  - docker run rocker/tidyverse /bin/sh -c "cd /root/tidyverse; bundle exec rake test"


#script:
#  - R -f inst/app/tests/run_shinyTest.R
# only report coverage for the release version
after_success:
# - Rscript -e 'library(vici)'
# - Rscript -e 'vici::run_app()'&
# - Rscript -e 'covr::codecov()'
# - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
  - docker stop $(docker ps -a -q)


jobs:
  include:
    - stage : "Test"
      name : "TestThat"
      script : test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'devtools::install(); testthat::test_dir("tests")'
    - stage : "deploy"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        target_branch: test_deploy
        on:
          branch: automTest
