# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

sudo: false
warnings_are_errors: false

matrix:
  include:
    - os: linux
      r: release

    - os: linux
      r: devel

    - os: osx
      r: release

r_packages:
- DT
- ggplot2
- grDevices
- magrittr
- ggpubr
- nlme
- shiny

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--as-cran --no-build-vignettes --no-manual --timings"

env:
  global:
  - _R_CHECK_TIMINGS_="0"
